name: Firefox Selenium Screenshot

on:
  push:
    branches:
      - main

jobs:
  capture_screenshot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Ensure this matches your Python script requirements

      - name: Install Firefox and geckodriver
        run: |
          sudo apt-get update
          sudo apt-get install firefox -y
          wget https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz
          tar -xvzf geckodriver-v0.30.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/geckodriver

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Run Selenium script
        run: |
          python3 <<EOF
          from selenium import webdriver
          import time

          options = webdriver.FirefoxOptions()
          options.headless = True

          driver = webdriver.Firefox(options=options)

          driver.get("https://www.whatismyipaddress.com")
          time.sleep(10)

          screenshot_path = "/tmp/screenshots/screenshot_firefox.png"
          driver.save_screenshot(screenshot_path)
          print(f"Screenshot saved to {screenshot_path}")

          driver.quit()
          EOF

      - name: Upload screenshot artifact
        if: success()  # Upload only if previous steps were successful
        uses: actions/upload-artifact@v2
        with:
          name: firefox-screenshot
          path: /tmp/screenshots/screenshot_firefox.png
