name: Docker Selenium Screenshot Test with Ngrok

on:
  push:
    branches:
      - main

jobs:
  run_container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step to create screenshots directory (if not exists)
      - name: Create screenshots directory
        run: mkdir -p screenshots

      # Step to start a Docker container with Selenium and capture a screenshot
      - name: Run Docker container
        run: |
          docker run -d --name test_container --network host selenium/standalone-chrome:latest bash -c "\
            mkdir -p /tmp/screenshots && \
            sleep 10 && \
            DISPLAY=:99 google-chrome --headless --disable-gpu --no-sandbox --disable-dev-shm-usage --screenshot=/tmp/screenshots/screenshot.png && \
            echo 'Screenshot taken' && \
            ls -l /tmp/screenshots && \
            mv /tmp/screenshots/*.png /tmp/screenshots/"
          sleep 10  # Ensure the container has enough time to take the screenshot

      # Step to move screenshot from the container to the host machine
      - name: Move screenshot to host
        run: |
          mkdir -p screenshots/test_container  # Ensure directory exists
          docker cp test_container:/tmp/screenshots/. screenshots/test_container/

      # Step to list screenshots for verification
      - name: List screenshots
        run: ls -R screenshots

      # Step to save screenshots as artifacts if they exist
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: screenshots
          if-no-files-found: error  # Fail workflow if no files are found
