name: Docker Puppeteer with Tor Screenshots

on:
  push:
    branches:
      - main

jobs:
  run_containers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1

      - name: Create screenshots directory
        run: mkdir -p screenshots

      - name: Run Tor Proxy Container
        run: |
          docker run -d --name tor_proxy --net=host --rm dperson/torproxy

      - name: Wait for Tor Proxy to Start
        run: sleep 10

      - name: Run Puppeteer Container and Capture Screenshots
        run: |
          for ((i=1; i<=5; i++)); do
            docker run -d --name puppeteer_$i \
              -v $(pwd)/screenshots:/screenshots \
              --net=host \
              alekzonder/puppeteer:latest \
              bash -c "\
                cd /tmp/screenshots && \
                node -e 'const puppeteer = require(\"puppeteer-extra\"); \
                          const StealthPlugin = require(\"puppeteer-extra-plugin-stealth\"); \
                          puppeteer.use(StealthPlugin()); \
                          (async () => { \
                            const browser = await puppeteer.launch({ \
                              headless: true, \
                              args: [ \
                                \"--proxy-server=socks5://localhost:9050\", \
                                \"--no-sandbox\", \
                                \"--disable-setuid-sandbox\" \
                              ] \
                            }); \
                            const page = await browser.newPage(); \
                            await page.goto(\"https://www.whatismyipaddress.com\"); \
                            await page.waitForTimeout(10000); // Wait for 10 seconds \
                            await page.screenshot({ path: \"/tmp/screenshots/screenshot_$i.png\" }); \
                            await browser.close(); \
                          })();'"

            sleep 12  # Allow time for Puppeteer to launch and capture screenshot

            docker cp puppeteer_$i:/tmp/screenshots/screenshot_$i.png screenshots/
            docker rm -f puppeteer_$i
          done

      - name: List screenshots
        run: ls -R screenshots

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: screenshots
          if-no-files-found: error

      - name: Cleanup Tor Proxy Container
        run: docker stop tor_proxy
