name: Docker Tor Browser Screenshots

on:
  push:
    branches:
      - main

jobs:
  run_containers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1

      - name: Create screenshots directory
        run: mkdir -p screenshots

      - name: Run Docker containers and capture screenshots
        run: |
          for ((i=1; i<=50; i++)); do
            docker run -d --name container_$i \
              -v $(pwd)/screenshots:/screenshots \
              --shm-size=2g \
              --privileged \
              jess/tor-browser \
              bash -c "\
                export DISPLAY=:99 && \
                Xvfb :99 -screen 0 1024x768x24 & \
                sleep 5 && \
                /usr/bin/tor-browser --headless --screenshot https://www.whatismyipaddress.com/ --output /screenshots/screenshot_$i.png && \
                echo 'Screenshot captured for container_$i'"

            sleep 10  # Adjust as necessary to wait for the screenshot capture
          done

      - name: List screenshots
        run: ls -R screenshots

      - name: Upload Artifacts
        if: success()  # Only run if previous steps were successful
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: screenshots
          if-no-files-found: error  # Fail workflow if no files are found
