name: Docker Tor Browser Screenshots

on:
  push:
    branches:
      - main

jobs:
  run_containers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1

      - name: Create screenshots directory
        run: mkdir -p screenshots

      - name: Run Docker containers and capture screenshots
        run: |
          for ((i=1; i<=50; i++)); do
            docker run -d --name container_$i \
              -v $(pwd)/screenshots:/screenshots \
              --net=host \
              dperson/torproxy \
              bash -c "\
                export DISPLAY=:99 && \
                Xvfb :99 -screen 0 1024x768x24 & \
                sleep 5 && \
                python3 -c 'from selenium import webdriver; \
                            options = webdriver.FirefoxOptions(); \
                            options.headless = True; \
                            profile = webdriver.FirefoxProfile(); \
                            profile.set_preference(\"network.proxy.type\", 1); \
                            profile.set_preference(\"network.proxy.socks\", \"localhost\"); \
                            profile.set_preference(\"network.proxy.socks_port\", 9050); \
                            driver = webdriver.Firefox(firefox_profile=profile, options=options); \
                            driver.get(\"https://www.whatismyipaddress.com/\"); \
                            driver.implicitly_wait(10); \
                            driver.save_screenshot(\"/screenshots/screenshot_$i.png\"); \
                            driver.quit();'"

            sleep 10  # Adjust as necessary to wait for the screenshot capture
          done

      - name: List screenshots
        run: ls -R screenshots

      - name: Upload Artifacts
        if: always()  # Always run this step, regardless of previous steps' outcome
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: screenshots
          if-no-files-found: error  # Fail workflow if no files are found
