name: Docker Selenium Screenshots with Ngrok

on:
  push:
    branches:
      - main

jobs:
  run_containers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step to install Ngrok
      - name: Install Ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc > /dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt-get update && sudo apt-get install ngrok

      # Step to start Ngrok tunnel
      - name: Start Ngrok Tunnel
        id: ngrok
        run: |
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          nohup ngrok http https://www.whatismyipaddress.com &
          sleep 16
          NGROK_URL=$(curl --silent --show-error http://127.0.0.1:4040/api/tunnels | jq -r .tunnels[0].public_url)
          echo $NGROK_URL

      # Step to create screenshots directory (if not exists)
      - name: Create screenshots directory
        run: mkdir -p screenshots

      # Step to start Docker containers with Selenium and capture screenshots
      - name: Run Docker containers
        run: |
          NGROK_URL=$(curl --silent --show-error http://127.0.0.1:4040/api/tunnels | jq -r .tunnels[0].public_url)
          for ((i=1; i<=50; i++)); do
            docker run -d --name container_$i --network host selenium/standalone-chrome:latest bash -c "\
              mkdir -p /tmp/screenshots && \
              cd /tmp/screenshots && \
              sleep 16 && \
              DISPLAY=:99 google-chrome --headless --disable-gpu --screenshot=/tmp/screenshots/$(date +%s)_screenshot.png ${NGROK_URL} && \
              mv /tmp/screenshots/*.png /tmp/screenshots/"
          done

      # Step to wait for containers to finish capturing screenshots
      - name: Wait for containers to complete
        run: sleep 60

      # Step to move screenshots from each container to host machine
      - name: Move screenshots to host
        run: |
          for ((i=1; i<=50; i++)); do
            mkdir -p screenshots/container_$i  # Ensure container_$i directory exists
            docker cp container_$i:/tmp/screenshots/. screenshots/container_$i/
          done

      # Step to list screenshots for verification
      - name: List screenshots
        run: ls -R screenshots

      # Step to save screenshots as artifacts if they exist
      - name: Upload Artifacts
        if: success()  # Only run if previous steps were successful
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: screenshots
          if-no-files-found: error  # Fail workflow if no files are found
