name: Firefox Selenium Screenshot

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  capture_screenshot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.5'  # Specify Python version
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium
        
      - name: Run Selenium script
        run: |
          python <<EOF
          from selenium import webdriver
          import time

          # Setup WebDriver options for Firefox
          options = webdriver.FirefoxOptions()
          options.headless = True

          # Start Firefox WebDriver
          driver = webdriver.Firefox(options=options)

          # Navigate to the webpage
          driver.get("https://www.whatismyipaddress.com")
          time.sleep(10)  # Wait for the page to load

          # Capture screenshot
          screenshot_path = "/tmp/screenshots/screenshot_firefox.png"
          driver.save_screenshot(screenshot_path)
          print(f"Screenshot saved to {screenshot_path}")

          # Quit WebDriver
          driver.quit()
          EOF

      - name: Upload screenshot artifact
        if: success()  # Upload only if previous steps were successful
        uses: actions/upload-artifact@v2
        with:
          name: firefox-screenshot
          path: /tmp/screenshots/screenshot_firefox.png
