name: Docker Chrome with Tor Screenshots

on:
  push:
    branches:
      - main

jobs:
  run_containers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1

      - name: Create screenshots directory
        run: mkdir -p screenshots

      - name: Run Docker containers with Chrome and Tor
        run: |
          for ((i=1; i<=5; i++)); do
            docker run -d --name container_$i \
              -v $(pwd)/screenshots:/screenshots \
              --net=host \
              --shm-size=2g \
              dperson/torproxy \
              tor

            sleep 15  # Give Tor time to start

            docker run -d --name chrome_$i \
              -v $(pwd)/screenshots:/screenshots \
              --net=host \
              --shm-size=2g \
              zenika/alpine-chrome:latest \
              google-chrome-stable \
                --headless \
                --disable-gpu \
                --no-sandbox \
                --disable-dev-shm-usage \
                --remote-debugging-port=9222 \
                --disable-software-rasterizer \
                --disable-setuid-sandbox \
                --user-data-dir=/tmp/chrome-home \
                --proxy-server=socks5://localhost:9050 \
                http://www.whatismyipaddress.com

            sleep 15  # Give Chrome time to start and connect through Tor

            docker exec chrome_$i google-chrome-stable \
              --headless \
              --disable-gpu \
              --no-sandbox \
              --disable-dev-shm-usage \
              --remote-debugging-port=9222 \
              --disable-software-rasterizer \
              --disable-setuid-sandbox \
              --user-data-dir=/tmp/chrome-home \
              --proxy-server=socks5://localhost:9050 \
              --screenshot=/screenshots/screenshot_$i.png \
              http://www.whatismyipaddress.com

            docker stop chrome_$i
            docker rm chrome_$i

            docker stop container_$i
            docker rm container_$i
          done

      - name: List screenshots
        run: ls -R screenshots

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: screenshots
          if-no-files-found: error
