name: Docker Selenium Screenshots with Puppeteer

on:
  push:
    branches:
      - main

jobs:
  run_containers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2r

      # Step to create screenshots directory (if not exists)
      - name: Create screenshots directory
        run: mkdir -p screenshots

      # Step to start Docker containers with Selenium and capture screenshots using Puppeteer
      - name: Run Docker containers
        run: |
          for ((i=1; i<=50; i++)); do
            docker run -d --rm --name container_$i \
              -v $(pwd)/screenshots:/screenshots \
              alekzonder/puppeteer:latest \
              bash -c "\
                mkdir -p /tmp/screenshots && \
                cd /tmp/screenshots && \
                sleep 10 && \
                node -e 'const puppeteer = require(\"puppeteer-extra\"); \
                          const StealthPlugin = require(\"puppeteer-extra-plugin-stealth\"); \
                          puppeteer.use(StealthPlugin()); \
                          (async () => { \
                            const browser = await puppeteer.launch(); \
                            const page = await browser.newPage(); \
                            await page.goto(\"https://www.whatismyipaddress.com\"); \
                            await page.screenshot({ path: \"/tmp/screenshots/screenshot.png\" }); \
                            await browser.close(); \
                          })();'"
            sleep 1
          done

      # Step to wait for containers to finish capturing screenshots
      - name: Wait for containers to complete
        run: sleep 60

      # Step to move screenshots from each container to host machine
      - name: Move screenshots to host
        run: |
          for ((i=1; i<=50; i++)); do
            mkdir -p screenshots/container_$i  # Ensure container_$i directory exists
            docker cp container_$i:/tmp/screenshots/. screenshots/container_$i/
          done

      # Step to list screenshots for verification
      - name: List screenshots
        run: ls -R screenshots

      # Step to save screenshots as artifacts if they exist
      - name: Upload Artifacts
        if: success()  # Only run if previous steps were successful
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: screenshots
          if-no-files-found: error  # Fail workflow if no files are found
