name: Docker Selenium Screenshots with Ngrok

on:
  push:
    branches:
      - main

jobs:
  run_containers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step to create screenshots directory (if not exists)
      - name: Create screenshots directory
        run: mkdir -p screenshots

      # Step to start Docker containers with Selenium and capture screenshots
      - name: Run Docker containers
        run: |
          for ((i=1; i<=4; i++)); do
            docker run -d --name container_$i selenium/standalone-chrome:latest bash -c "\
              mkdir -p /tmp/screenshots && \
              sleep 10 && \
              DISPLAY=:99 google-chrome --headless --disable-gpu --no-sandbox --disable-dev-shm-usage --screenshot=/tmp/screenshots/$(date +%s)_screenshot.png \
              mv /tmp/screenshots/*.png /tmp/screenshots/"
          done

      # Step to wait for containers to finish capturing screenshots
      - name: Wait for containers to complete
        run: sleep 120

      # Step to move screenshots from each container to host machine
      - name: Move screenshots to host
        run: |
          for ((i=1; i<=4; i++)); do
            mkdir -p screenshots/container_$i  # Ensure container_$i directory exists
            docker cp container_$i:/tmp/screenshots/. screenshots/container_$i/
          done

      # Step to list screenshots for verification
      - name: List screenshots
        run: ls -R screenshots

      # Step to save screenshots as artifacts if they exist
      - name: Upload Artifacts
        if: success()  # Only run if previous steps were successful
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: screenshots
          if-no-files-found: error  # Fail workflow if no files are found
